config/routes.rb
Annieslist2::Application.routes.draw do

  resources :locations do
    resources :restaurants do
      resources :visits, :only => [:create, :destroy]
    end
  end

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout"}

  devise_scope :user do 
    match "/" => "devise/sessions#new"
  end 

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :restaurants, :dependent => :destroy

  accepts_nested_attributes_for :restaurants
  
  attr_accessible :name, :restaurants_attributes
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :name, :link, :address, :phone, :location_id 
  belongs_to :location
  has_many :visits, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :visits, :dependent => :destroy
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :restaurant_id, :user_id, :id
  belongs_to :user 
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  #redirect after login
  def after_sign_in_path_for(resource)
    locations_path
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_restaurants_path(@location), notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :find_location
    
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = @location.restaurants.create(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to location_restaurants_path(@location), notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to location_path(@restaurant.location_id), notice: @restaurant.name + ' was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #
  # need to delete visits based on this restaurant!
  #
  
  def destroy

    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to location_restaurants_path(@restaurant.location_id), notice: @restaurant.name + ' was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  private
  
  def find_location
    @location = Location.find(params[:location_id])
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_filter :find_location
  before_filter :find_restaurant
  before_filter :find_user
     
  def create

    @visit = Visit.new(:user_id => @user.id, :restaurant_id => @restaurant.id)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to location_restaurants_path(@location) + "##{@restaurant.id.to_s}" }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @visit = Visit.find_by_user_id_and_restaurant_id(@user.id, @restaurant.id)
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to location_restaurants_path(@location) + "##{@restaurant.id.to_s}" }
      format.json { head :no_content }
    end
  end
  
  private

  def find_location
    @location = Location.find(params[:location_id])
  end
  
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def find_user
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-24374907-5']);
    _gaq.push(['_setDomainName', 'restaurantchecklist.net']);
    _gaq.push(['_trackPageview']);
  
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();  
  </script>

  <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
  <title>Restaurant Checklist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
    <% if false #user_signed_in? %>
	<div id="welcome">Welcome, <%= current_user.email %>!</div>
	<% end %>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	
    <div id="logo">
	  <% if user_signed_in? %>
  	    <a href="<%= locations_path %>" title="Click for all locations"><span>☑<strong>RestaurantChecklist</strong>.net</span></a>
	  <% else %>
	    <span>☑<strong>RestaurantChecklist</strong>.net</span>
	  <% end %>
    </div>

  <div id="content">

    
    <div id="user_nav">
	  <%= link_to "Back", :back, :title => "Go back" %> |
	  <a href="mailto:info@restaurantchecklist.net" title="Composes an email">Contact Us</a> |
      <% if user_signed_in? %>
		<% # current_user.email %>
        <%= link_to "Account", edit_user_registration_path, :title => current_user.email %> |
        <%= link_to "Logout", destroy_user_session_path, :method => 'DELETE', :title => "Come again soon!" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, :title => "For returning users" %> or <%= link_to "Register", new_user_registration_path, :title => "For new users" %>
      <% end %>
    </div>

    <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Pick a location</h1>
<table>
<% @locations.sort_by{|location| location.name}.each do |location| %>
  <tr>
    <td class="location"><%= link_to location.name, location_restaurants_path(location) %></td>
    <% if current_user.admin? %>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<%= if current_user.admin? then link_to 'New Location', new_location_path end %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back to locations', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<%= link_to 'Restaurants', location_restaurants_path(@location) %> |
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back to locations', locations_path %>

app/views/restaurants/_form.html.erb
<%= form_for [@location, @restaurant] do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', location_restaurants_path(@location) %>

app/views/restaurants/index.html.erb
<h1>Restaurants in <%= @location.name %></h1>
<table>
<% @location.restaurants.sort_by{|restaurant| restaurant.name}.each do |restaurant| %>
  <tr id="<%= restaurant.id %>">
    <% @visit = Visit.find_by_user_id_and_restaurant_id(current_user.id, restaurant.id) %>
    <td><% if @visit == nil %>  
      <%= link_to "☐", location_restaurant_visits_path(@location, restaurant), method: :create, :class => 'monospace', :title => "Click to mark visited" %>
    <% else %>  
      <%= link_to "☑", location_restaurant_visit_path(@location, restaurant,@visit.id), method: :delete, :class => 'monospace', :title => "Click to mark unvisited" %>
    <% end %></td>

    <td class="restaurant">
      <% if restaurant.link? %>
	    <a class="website" href="<%= restaurant.link %>" target="_blank" title="Click to open restaurant's website in new window">
          <%= restaurant.name %>
        </a>
      <% else %>
        <%= restaurant.name %>
      <% end %>
    </td>

    <td>
	  <% if restaurant.phone? %>
	    <a class="map" href="https://maps.google.com/maps?q=<%= restaurant.name %>+<%= restaurant.address %>" target="_blank" title="Click to view map in new window">
	      <%= restaurant.address %>
	    </a>
      <% end %>
	</td>
    <td>
	  <% if restaurant.phone? %>
	    <a class="tel" href="tel:<%= restaurant.phone %>" title="On mobile, tap to call">
	      <%= restaurant.phone %>
	    </a>
	  <% end %>
	</td>
    
    <% if current_user.admin? %>
      <td>
        <%= link_to 'Edit', edit_location_restaurant_path(@location, restaurant) %>
      </td>
      <td>
        <%= link_to 'Delete', location_restaurant_path(@location, restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    <% end %>

  </tr>
<% end %>
</table>
<br />

<%= if current_user.admin? then link_to 'New Restaurant', new_location_restaurant_path end %>
<%= if current_user.admin? then ' |' end %>
<%= link_to "Back", locations_path, :title => "Back to all locations" %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', location_restaurants_path(@location) %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>Nothing to see here.</p>

<%= link_to 'Edit', edit_location_restaurant_path(@location, @restaurant) %> |
<%= link_to 'Back', location_restaurants_path(@location) %>